# Site settings
title: Jeff Boek
email: jeff@jeffboek.com
description: "stuff and stuff"
baseurl: "http://jeffboek.com"
url: "http://jeffboek.com"
twitter_username: jeffboek
github_username:  boek

# Build settings
markdown: kramdown
permalink: pretty
