# Site settings
title: Jeff Boek
email: jeff@jeffboek.com
description: "stuff and stuff"
baseurl: ""
url: "http://jeffboek.com"
twitter_username: jeffboek
github_username:  boek
exclude: [vendor]

# Build settings
markdown: kramdown
permalink: pretty
