# Site settings
name: "SpiltCocoa"
email: "jeff@jeffboek.com"
description: "chocolate goodness"
baseurl: ""
url: "http://spiltcocoa.com"
twitter_username: jeffboek
github_username:  boek
exclude: [vendor, README.md, CNAME, Gemfile]

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: :title
